### ISSUE TITLE
Library bundle for easier consumption across modules

### ISSUE THREAD

**Issue by haroldma** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#19]
In our application we have various projects that are bundle independently and we would like to be able to use this library across all of them.

But the npm package does not come with a UMD bundle that we could set as an external in webpack.

**Comment by KeesCBakker** [comment]
Hi @haroldma, I've never used webpack. How hard is it to make such a bundle?

**Comment by KeesCBakker** [comment]
I'm not sure but I think we have to add something to [ste-browser](https://github.com/KeesCBakker/Strongly-Typed-Events-for-TypeScript/tree/master/packages/ste-browser).  These contain all the files that can be used in the browser (created using browserify and uglifyjs).

**Comment by haroldma** [comment]
It *should* be pretty straightforward. I'll see if later tonight I can get a PR out configuring it.

**Comment by haroldma** [comment]
So, how do you normally build ste-browser? Running `build` fails since there's no src folder.

BTW you should consider looking into [`rush`](https://www.npmjs.com/package/@microsoft/rush), since you're managing so many npm packages in one repo.

**Comment by KeesCBakker** [comment]
Great catch! The .js files of the package were ignored. They are now part of the repo per [82749c8](https://github.com/KeesCBakker/Strongly-Typed-Events-for-TypeScript/commit/de1856dd29293a0aac2da0de33c30deaaa73626f).

I'm building the project using Lerna. This will keep all packages in check. Invidual packages are build by doing an `npm run build`. When I want to build all packages I'll use `lerna run build` and when I'm publishing the packages I will publish them doing a `npm run make` on the root package (this will kick the builds, unit tests, version bump and actual publishing).

Currently I'm using Lerna, because the teams at my work use it as well.

**Comment by haroldma** [comment]
Gotcha. Rush is a similar tool but it also does linking across projects. So it never npm install any dependencies inside the project but creates a syslink under node_modules for it. Pretty handy.

Here's a quick PR setting webpack up. #20

**Comment by KeesCBakker** [comment]
Thanks for the PR, I'll take a look on it.

Lerna does the following:
- npm install all external dependencies of each package.
- _Symlink together all Lerna packages that are dependencies of each other._
- npm run prepublish in all bootstrapped packages.
- npm run prepare in all bootstrapped packages.

Looks similar. If Rush is faster or easier, I'll be happy to add it.

**Comment by haroldma** [comment]
Oh, pretty similar indeed. I have no experience with lerna but if it's working for you keep it.

I recommend rush at first since thinking you didn't have a system like that set up :)

**Comment by KeesCBakker** [comment]
Should be fixed by merge.

**Comment by KeesCBakker** [comment]
Thanks @haroldma!
