### ISSUE TITLE
Add support for `thisArg`

### ISSUE THREAD

**Issue by babakks** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#28]
Due to the nature of JavaScript, method contexts (i.e., `this` reference) could change depending on the way of invocation. In STE, using `subscribe` or `sub` without binding the listener method to the calling context would result in unexpected results.

For example:
```ts
import { ISimpleEvent, SimpleEventDispatcher } from "ste-simple-events";

const event = new SimpleEventDispatcher();
const foo = new Foo();
event.subscribe(foo.bar); // Dynamic-context subscription.
event.subscribe(foo.bar.bind(foo)); // Static-context subscription.
event.dispatch();

class Foo {
  dummy = 1;
  bar() { console.log(this.dummy); }
}
```

Here, the first subscription results in unexpected behavior due to its dynamic context, however, this is not totally unexpected due to the nature of the language.

Currently I'm using the binding method (second subscription), but it would be better for STE to take another argument as `thisArg` to hold the context and do the binding behind the scene, which complies with the current well-known conventions in the JS/TS community. Obviously, the argument is meant to be optional.

**Comment by KeesCBakker** [comment]
Makes sense, but I'm not totally sure how to implement this. Could you create a PR for this?

**Comment by KeesCBakker** [comment]
@babakks, I'm closing this issue. If you have a PR, I'm happy to look at it.

**Comment by OkanPinar** [comment]
Hello,

I know it is closed and old however it is a requirement i think. Can function context be added as optional parameter to the subscription function?
```
subscribe = function ( fn:function, context?: any): void {
      if (context) {
          _dispatcher.push(callback.bind(context));
      }
      else{
          _dispatcher.push(callback);
      }
}
```

**Comment by Kassenzettel** [comment]
Hello,

@babakks 
I love your eventsystem package and would be happy, to get the optional "context" parameter in a future version. Are you already working on that?  As a workaround I use actually an arrow function to get the instance of the class, what the event is subscribed.


Instead of 
..
this.foo.onBar.subscribe(bar);
...

I did something like that:
....
  this.foo.onBar.subscribe(() => {
                this.bar(this); // my callcback function placed in same object instance, could also be a method of any other object
            });
....

// Callback function 
private function bar(context:any) {           // any is placehold for type of the "context" class
   console.log(context); 
}

...

**Comment by KeesCBakker** [comment]
Happy to look at a PR if somebody implements this feature.
